# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibuq3yXRwuUgrtGl-QWpXjSiRtO9TYou
"""

import os
import numpy as np
import streamlit as st
import tensorflow as tf
from PIL import Image
import gdown


st.set_page_config(
    page_title="Color Theory Analysis AI",
    page_icon="🎨",
    layout="centered"
)

MAJOR_ID  = "1LMMFEspQL5GO-mBQuN_0E_0q9nbV9NuL"
SPRING_ID = "1GSr-7jHuRZsZw1iZAco2pcylRPU-IZWZ"
SUMMER_ID = "1-9OaA2r3Hjk_tFls0ZVnRl4OrZi70ErM"
AUTUMN_ID = "1CTKT-tiTsLBJXFAw-mF5-uxQcL7gLn4u"
WINTER_ID = "18e17Jzn1MhKAAZtEXJ69KxnhnYtx14CD"

MODEL_DIR = "models"
os.makedirs(MODEL_DIR, exist_ok=True)


MAJOR_PATH  = os.path.join(MODEL_DIR, "major_model.h5")
SPRING_PATH = os.path.join(MODEL_DIR, "spring_model.h5")
SUMMER_PATH = os.path.join(MODEL_DIR, "summer_model.h5")
AUTUMN_PATH = os.path.join(MODEL_DIR, "autumn_model.h5")
WINTER_PATH = os.path.join(MODEL_DIR, "winter_model.h5")

IMG_SIZE = 224


major_classes = ["autumn", "spring", "summer", "winter"]

spring_classes = [
    "bright_spring",
    "light_spring",
    "true_spring"
]

summer_classes = [
    "light_summer",
    "soft_summer",
    "true_summer"
]

autumn_classes = [
    "dark_autumn",
    "soft_autumn",
    "true_autumn"
]

winter_classes = [
    "bright_winter",
    "dark_winter",
    "true_winter"
]


def download_if_missing(file_id, out_path):
    if os.path.exists(out_path) and os.path.getsize(out_path) > 0:
        return
    url = f"https://drive.google.com/uc?id={file_id}"
    with st.spinner(f"Downloading {os.path.basename(out_path)}..."):
        gdown.download(url, out_path, quiet=False)


@st.cache_resource
def load_models():
    download_if_missing(MAJOR_ID, MAJOR_PATH)
    download_if_missing(SPRING_ID, SPRING_PATH)
    download_if_missing(SUMMER_ID, SUMMER_PATH)
    download_if_missing(AUTUMN_ID, AUTUMN_PATH)
    download_if_missing(WINTER_ID, WINTER_PATH)

    major  = tf.keras.models.load_model(MAJOR_PATH)
    spring = tf.keras.models.load_model(SPRING_PATH)
    summer = tf.keras.models.load_model(SUMMER_PATH)
    autumn = tf.keras.models.load_model(AUTUMN_PATH)
    winter = tf.keras.models.load_model(WINTER_PATH)

    return major, spring, summer, autumn, winter


def preprocess_image(pil_img):
    pil_img = pil_img.resize((IMG_SIZE, IMG_SIZE))
    arr = np.asarray(pil_img).astype("float32")
    return np.expand_dims(arr, axis=0)


def soft_table(labels, probs):
    pairs = list(zip(labels, probs))
    pairs.sort(key=lambda x: x[1], reverse=True)
    return [{"class": k, "confidence_%": round(v * 100, 1)} for k, v in pairs]


def predict(image, major_m, spring_m, summer_m, autumn_m, winter_m):
    x = preprocess_image(image)

    major_probs = major_m.predict(x, verbose=0)[0]
    major_idx = int(np.argmax(major_probs))
    major_label = major_classes[major_idx]
    major_conf = float(major_probs[major_idx])

    if major_label == "spring":
        sub_model, sub_labels = spring_m, spring_classes
    elif major_label == "summer":
        sub_model, sub_labels = summer_m, summer_classes
    elif major_label == "autumn":
        sub_model, sub_labels = autumn_m, autumn_classes
    else:
        sub_model, sub_labels = winter_m, winter_classes

    sub_probs = sub_model.predict(x, verbose=0)[0]
    sub_idx = int(np.argmax(sub_probs))
    sub_label = sub_labels[sub_idx]
    sub_conf = float(sub_probs[sub_idx])

    return {
        "major_label": major_label,
        "major_conf": major_conf,
        "major_soft": soft_table(major_classes, major_probs),
        "sub_label": sub_label,
        "sub_conf": sub_conf,
        "sub_soft": soft_table(sub_labels, sub_probs),
    }

st.title("🎨 Color Theory Analysis AI")
st.write("Upload a photo to get your Major Season, Subseason, and confidence scores.")

major_m, spring_m, summer_m, autumn_m, winter_m = load_models()
st.success("Models loaded")

uploaded = st.file_uploader(
    "Upload a JPG or PNG",
    type=["jpg", "jpeg", "png"],
    key="uploader"
)

if uploaded is None:
    st.info("Upload an image to begin.")
    st.stop()

image = Image.open(uploaded).convert("RGB")
image = image.copy()

st.image(image, caption="Uploaded image", use_container_width=True)

out = predict(image, major_m, spring_m, summer_m, autumn_m, winter_m)

st.subheader("Prediction")
st.write(f"**Major Season:** {out['major_label'].upper()} — **{out['major_conf']*100:.1f}%**")
st.write(f"**Subseason:** {out['sub_label'].upper()} — **{out['sub_conf']*100:.1f}%**")

c1, c2 = st.columns(2)
with c1:
    st.markdown("### Major season probabilities")
    st.dataframe(out["major_soft"], hide_index=True, use_container_width=True)
with c2:
    st.markdown("### Subseason probabilities")
    st.dataframe(out["sub_soft"], hide_index=True, use_container_width=True)

if out["major_conf"] < 0.55 or out["sub_conf"] < 0.4:
    st.warning("Low confidence — try a clearer, front-facing photo in natural light.")